### ISSUE TITLE
Production Build

### ISSUE THREAD

**Issue by srinivasmaram2025** [webexpe13/blog-template-using-nextjs-typescript-tailwindcss#9]
How can Use it Template For Production Build

**Comment by webexpe13** [comment]
Yes sure, just tell us the website so that we can add this in our demo
list.

**Comment by srinivasmaram2025** [comment]
Blog application using nextjs and type script


I want to Use Your Template for My Blog application, How to generate production folder to host on live.
..

**Comment by webexpe13** [comment]
Run the export comand, it will generate the out folder. That is the static
build folder you can upload on your server.

There is an entire article on the demo website on how to export and deploy
on firebase.

https://nextjs-simple-blog-template.web.app/tutorial/how-to-deploy-blog/

**Comment by srinivasmaram2025** [comment]
Thanks...

**Comment by srinivasmaram2025** [comment]
D:\Full Stack\Pro Mern Stack\NextJS\blog-template-using-nextjs-typescript-tailwindcss>npm run out

> nextjs-simple-blog-template@0.1.0 out
> next build && next export

info  - Checking validity of types

Failed to compile.

./src/components/Navbar/Centered.tsx
120:13  Error: Missing "key" prop for element in iterator  react/jsx-key

./src/components/Navbar/NavSideBar.tsx
57:33  Error: Missing "key" prop for element in iterator  react/jsx-key

./src/components/Navbar/SimpleNavbar.tsx
50:17  Error: Missing "key" prop for element in iterator  react/jsx-key

./src/components/Slider/index.tsx
26:25  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules


It Shows error like this, How can i Debug.

**Comment by webexpe13** [comment]
Hi,

For slider alt test warning just add an alt="" to image tag.
./src/components/Slider/index.tsx
26:25 Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images. jsx-a11y/alt-text
example: `<img src='' alt='some alt text' ... />`

For the rest 3 bugs
./src/components/Navbar/Centered.tsx
./src/components/Navbar/NavSideBar.tsx
./src/components/Navbar/SimpleNavbar.tsx

you might have run a loop in jsx whithout giving a key to the element. in react we need to pass a key if we are rendering thru a loop.

eample:
` {
                array.map(each => (
                    <div key={each.id}>
                        .....
                    </div>
                ))
            }`

please check your code and let me know if you need any more help.
